### PR TITLE
Level editor improvements

### LINKED ISSUE #29: Level-Editor Start Platform Area
2Tiles above StartPlatform no other block should be allowed(otherwise player spawns in block)

### LINKED ISSUE #30: Level-Editor wasd movement

### LINKED ISSUE #33: Keep selected block colored
Change from button to toggle

### LINKED ISSUE #35: chainblocks in the editor not updating
when replacing chainblocks in the editor (with chainblocks of a different ID), nothing happens. the old id stays.

### LINKED ISSUE #40: LevelEditor Set-GridSize
Add "new button" to generate grid for editor

### LINKED ISSUE #41: LevelEditor - LoadLevel choose from windows thing

### PR DESCRIPTION
**Pull request by lee17017**
LevelEditor now starts with an menu where players can choose to edit an existing level or create a new one / delete old ones. When creating new level you can enter name and dimensions (min 7, max 99) [close #41 and close #40 ]

BlockSelection now uses a scrollRect(copy one block to test it out).
BlockSelection now uses toggles(currently selected button is highlighted by border, starting with wood). [closes #33]
Removed some options in MenuBar - remaining: LevelName updates name and renames file, Save: saves, Test: not implemented yet, Exit: goes back to Editormenu

When going into edit mode: Camera set to max Zoomout and centered on level
ZoomIn/out with mousewheel - move Camera with WASD / mouse rightClick and hold(I dont know if this should be inverted or not)
Zooming / moving should not work when mouse is over GUI / in Inputfield
Camera moveable until edges(so that the last block is in center of camera screen)
I did not add arrows as it should be clear with the initial zoomed out view. [closes #30]

ChainBlocks have different Colors depending on Id + fixed problem with overwriting[closes #35]

Area above startplatform cannot be replaced[closes #29]

Added BlockDescriptionText under MenuBar - shows when hovering above block

Colors / ButtonHighlights / other stuff - not final (I am lazy and it turned out to be more than expected)

### CODE REVIEW

**Comment by JonlineRB** [comment]
-I find the last 2 variants of chainblocks indistinguishable (color blindedness?), but we are missing an obvious white variant. Should I make a white texture? I think it would work better

**Comment by JonlineRB** [comment]
- WASD camera controls in the editor - perfect.
- right click canera controls in the editor - suboptimal. I would consider this very nice to have since WASD is perfectly servicable.

**Review by JonlineRB — APPROVED** [review]
Good job on the scrolling in the level selection

**Review by MarcoTUM — APPROVED** [review]

**Comment by JonlineRB** [comment]
Scrolling of blocks in the editor still doesn't work.

Maybe we should schedule a session to see why this fails? I'm assuming this worked for you locally?

**Pull request merged**
