### PR TITLE
Background

### PR DESCRIPTION
**Pull request by JonlineRB**
Revamped background:

Replaced texture
added swappable tiles that take random variations of the base background texture with astronomy like star constelations. 5 tiles will be randomly placed in the background.

As of now, duplication may occour both in positions and in the textures.

Let me know if you guys like this direction. If so I will enhance the code to remove the duplications.

### CODE REVIEW

**Review by lee17017 — CHANGES_REQUESTED** [review]
Looks good - maybe a little bit of transparency on the signs

The main thing is that the background does not adapt to the size of the level(currently if the level is too big we can reach the end of the plane I think)

**Review by MarcoTUM — APPROVED** [review]
PlayScene changes might lead to merge conflicts.

**Comment by JonlineRB** [comment]
Update:

Please test in the playscene_backgroundCopy scene.

The backgroundComposer will generate backround tiles based on the textures stored in it's array.

**Review by lee17017 — APPROVED** [review]
Nice Work - Can you merge the master into your branch and put the prefab in the playScene and test if the edges are still not visible? I changed the camera settings a bit in my branch.

**Pull request merged**
